"use strict";

var _classCallCheck2 = require("babel-runtime/helpers/classCallCheck");

var _classCallCheck3 = _interopRequireDefault(_classCallCheck2);

var _possibleConstructorReturn2 = require("babel-runtime/helpers/possibleConstructorReturn");

var _possibleConstructorReturn3 = _interopRequireDefault(_possibleConstructorReturn2);

var _inherits2 = require("babel-runtime/helpers/inherits");

var _inherits3 = _interopRequireDefault(_inherits2);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

// Generated by CoffeeScript 2.2.4
(function () {
  var BottleneckError;

  BottleneckError = function (_Error) {
    (0, _inherits3.default)(BottleneckError, _Error);

    function BottleneckError() {
      (0, _classCallCheck3.default)(this, BottleneckError);
      return (0, _possibleConstructorReturn3.default)(this, (BottleneckError.__proto__ || Object.getPrototypeOf(BottleneckError)).apply(this, arguments));
    }

    return BottleneckError;
  }(Error);

  module.exports = BottleneckError;
}).call(undefined);