"use strict";

var _classCallCheck2 = require("babel-runtime/helpers/classCallCheck");

var _classCallCheck3 = _interopRequireDefault(_classCallCheck2);

var _createClass2 = require("babel-runtime/helpers/createClass");

var _createClass3 = _interopRequireDefault(_createClass2);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

// Generated by CoffeeScript 2.2.4
(function () {
  var DLList;

  DLList = function () {
    function DLList() {
      (0, _classCallCheck3.default)(this, DLList);

      this._first = null;
      this._last = null;
      this.length = 0;
    }

    (0, _createClass3.default)(DLList, [{
      key: "push",
      value: function push(value) {
        var node;
        this.length++;
        node = {
          value: value,
          next: null
        };
        if (this._last != null) {
          this._last.next = node;
          this._last = node;
        } else {
          this._first = this._last = node;
        }
        return void 0;
      }
    }, {
      key: "shift",
      value: function shift() {
        var ref1, value;
        if (this._first == null) {
          return void 0;
        } else {
          this.length--;
        }
        value = this._first.value;
        this._first = (ref1 = this._first.next) != null ? ref1 : this._last = null;
        return value;
      }
    }, {
      key: "first",
      value: function first() {
        if (this._first != null) {
          return this._first.value;
        }
      }
    }, {
      key: "getArray",
      value: function getArray() {
        var node, ref, results;
        node = this._first;
        results = [];
        while (node != null) {
          results.push((ref = node, node = node.next, ref.value));
        }
        return results;
      }
    }]);
    return DLList;
  }();

  module.exports = DLList;
}).call(undefined);