"use strict";

// Generated by CoffeeScript 2.2.4
(function () {
  exports.load = function (received, defaults) {
    var onto = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : {};

    var k, ref, v;
    for (k in defaults) {
      v = defaults[k];
      onto[k] = (ref = received[k]) != null ? ref : v;
    }
    return onto;
  };

  exports.overwrite = function (received, defaults) {
    var onto = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : {};

    var k, v;
    for (k in received) {
      v = received[k];
      if (defaults[k] !== void 0) {
        onto[k] = v;
      }
    }
    return onto;
  };
}).call(undefined);